# Generated by Django 5.1 on 2024-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_P', models.CharField(max_length=100)),
                ('apellido_M', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('pedido', models.CharField(max_length=100)),
            ],
        ),
    ]
